name: Print PR Patch Content

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  local-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: "smart-review"
    - name: npm install
      run: |
        cd smart-review
        npm install
    - name: Print patch content
      uses: ./smart-review
      with:
        apiKey: ${{ secrets.OPENAI_API_KEY }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}